; Target assembler: 64tass v1.59.3120 [--ascii --case-sensitive -Wall]
; 6502bench SourceGen v1.10.0
        .cpu    "6502"
*       =       $1001
        .byte   $0b
        .byte   $10
        .byte   $01
        .byte   $00
        .text   $9e,"4110"
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $78
        .byte   $a9
        .byte   $7f
        .byte   $8d
        .byte   $1e
        .byte   $91
        .byte   $20
        .byte   $68
        .byte   $1b
        .byte   $20
        .byte   $91
        .byte   $14
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $05
        .byte   $90
        .byte   $ad
        .byte   $11
        .byte   $91
        .byte   $49
        .byte   $ff
        .byte   $29
        .byte   $20
        .byte   $f0
        .byte   $08
        .byte   $ad
        .byte   $00
        .byte   $90
        .byte   $09
        .byte   $80
        .byte   $8d
        .byte   $00
        .byte   $90
        .byte   $38
        .byte   $08
        .byte   $20
        .byte   $cc
        .byte   $16
        .byte   $20
        .byte   $8e
        .byte   $14
        .byte   $28
        .byte   $90
        .byte   $03
        .byte   $20
        .byte   $a9
        .byte   $10
        .byte   $20
        .byte   $a6
        .byte   $14
        .byte   $a9
        .byte   $56
        .byte   $a0
        .byte   $13
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $8c
        .byte   $15
        .byte   $03
        .byte   $78
        .byte   $2c
        .byte   $bb
        .byte   $1b
        .byte   $10
        .byte   $19
        .byte   $20
        .byte   $c6
        .byte   $16
        .byte   $20
        .byte   $99
        .byte   $19
        .byte   $20
        .byte   $a9
        .byte   $14
        .byte   $ce
        .byte   $88
        .byte   $1b
        .byte   $30
        .byte   $24
        .byte   $20
        .byte   $a3
        .byte   $14
        .byte   $20
        .byte   $a6
        .byte   $14
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $bb
        .byte   $1b
        .byte   $ad
        .byte   $ba
        .byte   $1b
        .byte   $c9
        .byte   $c5
        .byte   $90
        .byte   $03
        .byte   $20
        .byte   $b7
        .byte   $16
        .byte   $2c
        .byte   $c1
        .byte   $1b
        .byte   $10
        .byte   $03
        .byte   $20
        .byte   $bd
        .byte   $16
        .byte   $58
        .byte   $ea
        .byte   $ea
        .byte   $ea
        .byte   $4c
        .byte   $4b
        .byte   $10
        .byte   $20
        .byte   $a9
        .byte   $10
        .byte   $a0
        .byte   $03
        .byte   $f8
        .byte   $38
        .byte   $b9
        .byte   $84
        .byte   $1b
        .byte   $f9
        .byte   $80
        .byte   $1b
        .byte   $88
        .byte   $10
        .byte   $f7
        .byte   $d8
        .byte   $90
        .byte   $0b
        .byte   $a0
        .byte   $03
        .byte   $b9
        .byte   $84
        .byte   $1b
        .byte   $99
        .byte   $80
        .byte   $1b
        .byte   $88
        .byte   $10
        .byte   $f7
        .byte   $20
        .byte   $94
        .byte   $14
        .byte   $18
        .byte   $08
        .byte   $4c
        .byte   $32
        .byte   $10
        .byte   $20
        .byte   $c6
        .byte   $16
        .byte   $ad
        .byte   $11
        .byte   $91
        .byte   $49
        .byte   $ff
        .byte   $29
        .byte   $20
        .byte   $d0
        .byte   $0c
        .byte   $85
        .byte   $c6
        .byte   $20
        .byte   $9f
        .byte   $ff
        .byte   $20
        .byte   $c2
        .byte   $10
        .byte   $c9
        .byte   $85
        .byte   $d0
        .byte   $eb
        .byte   $60
        .byte   $a5
        .byte   $c6
        .byte   $f0
        .byte   $11
        .byte   $ac
        .byte   $77
        .byte   $02
        .byte   $a2
        .byte   $00
        .byte   $bd
        .byte   $78
        .byte   $02
        .byte   $9d
        .byte   $77
        .byte   $02
        .byte   $e8
        .byte   $e4
        .byte   $c6
        .byte   $d0
        .byte   $f5
        .byte   $98
        .byte   $60
        .byte   $ad
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $48
        .byte   $ad
        .byte   $aa
        .byte   $1b
        .byte   $85
        .byte   $fa
        .byte   $48
        .byte   $ac
        .byte   $b8
        .byte   $1b
        .byte   $20
        .byte   $0f
        .byte   $12
        .byte   $c9
        .byte   $0b
        .byte   $b0
        .byte   $17
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $68
        .byte   $85
        .byte   $f9
        .byte   $48
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $ac
        .byte   $ab
        .byte   $1b
        .byte   $20
        .byte   $0f
        .byte   $12
        .byte   $c9
        .byte   $0b
        .byte   $b0
        .byte   $03
        .byte   $68
        .byte   $68
        .byte   $60
        .byte   $f0
        .byte   $33
        .byte   $c9
        .byte   $0c
        .byte   $f0
        .byte   $45
        .byte   $c9
        .byte   $10
        .byte   $b0
        .byte   $03
        .byte   $4c
        .byte   $ac
        .byte   $11
        .byte   $c9
        .byte   $18
        .byte   $90
        .byte   $61
        .byte   $b9
        .byte   $0b
        .byte   $12
        .byte   $8c
        .byte   $ab
        .byte   $1b
        .byte   $a2
        .byte   $07
        .byte   $38
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $a5
        .byte   $f9
        .byte   $8d
        .byte   $a9
        .byte   $1b
        .byte   $a5
        .byte   $fa
        .byte   $8d
        .byte   $aa
        .byte   $1b
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $68
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $38
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $a9
        .byte   $10
        .byte   $a2
        .byte   $00
        .byte   $20
        .byte   $d1
        .byte   $11
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $bf
        .byte   $1b
        .byte   $a9
        .byte   $06
        .byte   $85
        .byte   $01
        .byte   $ce
        .byte   $ba
        .byte   $1b
        .byte   $4c
        .byte   $16
        .byte   $11
        .byte   $a9
        .byte   $50
        .byte   $a2
        .byte   $00
        .byte   $20
        .byte   $d1
        .byte   $11
        .byte   $a9
        .byte   $01
        .byte   $8d
        .byte   $bd
        .byte   $1b
        .byte   $a9
        .byte   $c0
        .byte   $8d
        .byte   $bc
        .byte   $1b
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $be
        .byte   $1b
        .byte   $a9
        .byte   $01
        .byte   $8d
        .byte   $90
        .byte   $1b
        .byte   $8d
        .byte   $a5
        .byte   $1b
        .byte   $8d
        .byte   $97
        .byte   $1b
        .byte   $8d
        .byte   $9e
        .byte   $1b
        .byte   $4c
        .byte   $16
        .byte   $11
        .byte   $38
        .byte   $e9
        .byte   $12
        .byte   $aa
        .byte   $bd
        .byte   $f5
        .byte   $11
        .byte   $aa
        .byte   $a9
        .byte   $00
        .byte   $20
        .byte   $d1
        .byte   $11
        .byte   $98
        .byte   $48
        .byte   $a5
        .byte   $f9
        .byte   $48
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $a9
        .byte   $e7
        .byte   $a0
        .byte   $1f
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a0
        .byte   $05
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $38
        .byte   $20
        .byte   $8b
        .byte   $14
        .byte   $88
        .byte   $10
        .byte   $f5
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $68
        .byte   $85
        .byte   $f9
        .byte   $68
        .byte   $a8
        .byte   $4c
        .byte   $16
        .byte   $11
        .byte   $2c
        .byte   $be
        .byte   $1b
        .byte   $10
        .byte   $18
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $c1
        .byte   $1b
        .byte   $ee
        .byte   $c2
        .byte   $1b
        .byte   $ae
        .byte   $c2
        .byte   $1b
        .byte   $ca
        .byte   $bd
        .byte   $fb
        .byte   $11
        .byte   $aa
        .byte   $a9
        .byte   $00
        .byte   $20
        .byte   $d1
        .byte   $11
        .byte   $4c
        .byte   $16
        .byte   $11
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $bb
        .byte   $1b
        .byte   $68
        .byte   $68
        .byte   $60
        .byte   $8d
        .byte   $8c
        .byte   $1b
        .byte   $8e
        .byte   $8b
        .byte   $1b
        .byte   $98
        .byte   $48
        .byte   $a5
        .byte   $f9
        .byte   $48
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $20
        .byte   $8e
        .byte   $14
        .byte   $a9
        .byte   $00
        .byte   $a0
        .byte   $03
        .byte   $99
        .byte   $89
        .byte   $1b
        .byte   $88
        .byte   $10
        .byte   $fa
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $68
        .byte   $85
        .byte   $f9
        .byte   $68
        .byte   $a8
        .byte   $60
        .byte   $20
        .byte   $05
        .byte   $20
        .byte   $10
        .byte   $02
        .byte   $01
        .byte   $01
        .byte   $02
        .byte   $04
        .byte   $08
        .byte   $16
        .text   "$2@hv"
        .byte   $64
        .byte   $72
        .byte   $01
        .byte   $96
        .byte   $16
        .byte   $81
        .byte   $0d
        .byte   $19
        .byte   $10
        .byte   $18
        .byte   $98
        .byte   $48
        .byte   $b9
        .byte   $07
        .byte   $12
        .byte   $30
        .byte   $0b
        .byte   $18
        .byte   $65
        .byte   $f9
        .byte   $85
        .byte   $f9
        .byte   $90
        .byte   $15
        .byte   $e6
        .byte   $fa
        .byte   $d0
        .byte   $11
        .byte   $29
        .byte   $7f
        .byte   $85
        .byte   $8f
        .byte   $38
        .byte   $a5
        .byte   $f9
        .byte   $e5
        .byte   $8f
        .byte   $85
        .byte   $f9
        .byte   $a5
        .byte   $fa
        .byte   $e9
        .byte   $00
        .byte   $85
        .byte   $fa
        .byte   $18
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $aa
        .byte   $68
        .byte   $a8
        .byte   $8a
        .byte   $60
        .byte   $a9
        .byte   $8d
        .byte   $a0
        .byte   $1b
        .byte   $20
        .byte   $57
        .byte   $12
        .byte   $a9
        .byte   $94
        .byte   $a0
        .byte   $1b
        .byte   $20
        .byte   $57
        .byte   $12
        .byte   $a9
        .byte   $9b
        .byte   $a0
        .byte   $1b
        .byte   $20
        .byte   $57
        .byte   $12
        .byte   $a9
        .byte   $a2
        .byte   $a0
        .byte   $1b
        .byte   $4c
        .byte   $57
        .byte   $12
        .byte   $85
        .byte   $8b
        .byte   $84
        .byte   $8c
        .byte   $a9
        .byte   $b0
        .byte   $a0
        .byte   $1b
        .byte   $85
        .byte   $8d
        .byte   $84
        .byte   $8e
        .byte   $a0
        .byte   $06
        .byte   $b1
        .byte   $8b
        .byte   $91
        .byte   $8d
        .byte   $88
        .byte   $10
        .byte   $f9
        .byte   $ad
        .byte   $14
        .byte   $91
        .byte   $29
        .byte   $03
        .byte   $18
        .byte   $6d
        .byte   $b4
        .byte   $1b
        .byte   $85
        .byte   $8f
        .byte   $c6
        .byte   $8f
        .byte   $e6
        .byte   $8f
        .byte   $a4
        .byte   $8f
        .byte   $b9
        .byte   $29
        .byte   $13
        .byte   $8d
        .byte   $b4
        .byte   $1b
        .byte   $4a
        .byte   $4a
        .byte   $4a
        .byte   $a8
        .byte   $b9
        .byte   $51
        .byte   $13
        .byte   $d0
        .byte   $03
        .byte   $4c
        .byte   $1f
        .byte   $13
        .byte   $30
        .byte   $0f
        .byte   $18
        .byte   $6d
        .byte   $b0
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $00
        .byte   $6d
        .byte   $b1
        .byte   $1b
        .byte   $85
        .byte   $fa
        .byte   $d0
        .byte   $13
        .byte   $29
        .byte   $7f
        .byte   $85
        .byte   $a7
        .byte   $38
        .byte   $ad
        .byte   $b0
        .byte   $1b
        .byte   $e5
        .byte   $a7
        .byte   $85
        .byte   $f9
        .byte   $ad
        .byte   $b1
        .byte   $1b
        .byte   $e9
        .byte   $00
        .byte   $85
        .byte   $fa
        .byte   $18
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $c9
        .byte   $1a
        .byte   $b0
        .byte   $2a
        .byte   $c9
        .byte   $00
        .byte   $d0
        .byte   $05
        .byte   $ac
        .byte   $b4
        .byte   $1b
        .byte   $f0
        .byte   $21
        .byte   $c9
        .byte   $0b
        .byte   $90
        .byte   $b1
        .byte   $c9
        .byte   $0d
        .byte   $f0
        .byte   $12
        .byte   $90
        .byte   $17
        .byte   $c9
        .byte   $10
        .byte   $f0
        .byte   $0c
        .byte   $90
        .byte   $a5
        .byte   $c9
        .byte   $11
        .byte   $f0
        .byte   $06
        .byte   $c9
        .byte   $18
        .byte   $f0
        .byte   $02
        .byte   $90
        .byte   $07
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $bb
        .byte   $1b
        .byte   $d0
        .byte   $43
        .byte   $48
        .byte   $8a
        .byte   $48
        .byte   $a5
        .byte   $f9
        .byte   $48
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $ad
        .byte   $b0
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $ad
        .byte   $b1
        .byte   $1b
        .byte   $85
        .byte   $fa
        .byte   $ad
        .byte   $b5
        .byte   $1b
        .byte   $ae
        .byte   $b6
        .byte   $1b
        .byte   $38
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $68
        .byte   $8d
        .byte   $b1
        .byte   $1b
        .byte   $85
        .byte   $fa
        .byte   $68
        .byte   $8d
        .byte   $b0
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $68
        .byte   $8d
        .byte   $b6
        .byte   $1b
        .byte   $68
        .byte   $8d
        .byte   $b5
        .byte   $1b
        .byte   $a9
        .byte   $0e
        .byte   $ae
        .byte   $b3
        .byte   $1b
        .byte   $38
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $a0
        .byte   $06
        .byte   $b1
        .byte   $8d
        .byte   $91
        .byte   $8b
        .byte   $88
        .byte   $10
        .byte   $f9
        .byte   $60
        .byte   $00
        .byte   $00
        .byte   $10
        .byte   $18
        .byte   $00
        .byte   $10
        .byte   $08
        .byte   $20
        .byte   $08
        .byte   $08
        .byte   $18
        .byte   $10
        .byte   $08
        .byte   $18
        .byte   $00
        .byte   $20
        .byte   $10
        .byte   $10
        .byte   $00
        .byte   $08
        .byte   $10
        .byte   $00
        .byte   $18
        .byte   $20
        .byte   $18
        .byte   $18
        .byte   $08
        .byte   $00
        .byte   $18
        .byte   $08
        .byte   $10
        .byte   $20
        .byte   $08
        .byte   $00
        .byte   $18
        .byte   $10
        .byte   $08
        .byte   $00
        .byte   $18
        .byte   $20
        .byte   $01
        .byte   $81
        .byte   $16
        .byte   $96
        .byte   $00
        .byte   $e6
        .byte   $3f
        .byte   $d0
        .byte   $02
        .byte   $e6
        .byte   $40
        .byte   $2c
        .byte   $be
        .byte   $1b
        .byte   $10
        .byte   $0e
        .byte   $20
        .byte   $ba
        .byte   $16
        .byte   $2c
        .byte   $be
        .byte   $1b
        .byte   $10
        .byte   $06
        .byte   $20
        .byte   $5f
        .byte   $14
        .byte   $4c
        .byte   $72
        .byte   $13
        .byte   $20
        .byte   $4b
        .byte   $14
        .byte   $20
        .byte   $9a
        .byte   $14
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $c6
        .byte   $20
        .byte   $9f
        .byte   $ff
        .byte   $20
        .byte   $c2
        .byte   $10
        .byte   $c9
        .byte   $45
        .byte   $f0
        .byte   $0f
        .byte   $c9
        .byte   $56
        .byte   $f0
        .byte   $0e
        .byte   $c9
        .byte   $4a
        .byte   $f0
        .text   $0d,"IlP"
        .byte   $0e
        .byte   $a9
        .byte   $00
        .byte   $2c
        .byte   $a9
        .byte   $01
        .byte   $2c
        .byte   $a9
        .byte   $02
        .byte   $2c
        .byte   $a9
        .byte   $03
        .byte   $8d
        .byte   $b8
        .byte   $1b
        .byte   $ce
        .byte   $ac
        .byte   $1b
        .byte   $10
        .byte   $08
        .byte   $a9
        .byte   $06
        .byte   $8d
        .byte   $ac
        .byte   $1b
        .byte   $20
        .byte   $c0
        .byte   $16
        .byte   $ce
        .byte   $ad
        .byte   $1b
        .byte   $10
        .byte   $17
        .byte   $a9
        .byte   $0c
        .byte   $8d
        .byte   $ad
        .byte   $1b
        .text   " ;",$12,","
        .byte   $bb
        .byte   $1b
        .byte   $10
        .byte   $0a
        .byte   $2c
        .byte   $be
        .byte   $1b
        .byte   $10
        .byte   $24
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $bb
        .byte   $1b
        .byte   $ce
        .byte   $ae
        .byte   $1b
        .byte   $10
        .byte   $08
        .byte   $a9
        .byte   $04
        .byte   $8d
        .byte   $ae
        .byte   $1b
        .byte   $20
        .byte   $9d
        .byte   $14
        .byte   $ce
        .byte   $af
        .byte   $1b
        .byte   $10
        .byte   $0d
        .byte   $a9
        .byte   $08
        .byte   $8d
        .byte   $af
        .byte   $1b
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $bf
        .byte   $1b
        .byte   $20
        .byte   $d8
        .byte   $10
        .byte   $20
        .byte   $1c
        .byte   $19
        .byte   $a5
        .text   "@I",$05,$90,"7"
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $3f
        .byte   $85
        .byte   $40
        .byte   $ad
        .byte   $a4
        .text   $1e,"I P*"
        .byte   $a9
        .byte   $a4
        .byte   $a0
        .byte   $1e
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $ad
        .byte   $14
        .byte   $91
        .text   ")",$07,"h @"
        .byte   $14
        .byte   $a9
        .byte   $e7
        .byte   $a0
        .byte   $1f
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $68
        .byte   $48
        .byte   $20
        .byte   $40
        .byte   $14
        .byte   $68
        .byte   $e6
        .byte   $f9
        .byte   $e6
        .byte   $f9
        .byte   $a8
        .byte   $b9
        .byte   $38
        .byte   $14
        .byte   $20
        .byte   $c3
        .byte   $16
        .byte   $4c
        .byte   $b4
        .byte   $16
        .byte   $12
        .byte   $14
        .byte   $13
        .byte   $15
        .byte   $17
        .byte   $16
        .byte   $17
        .byte   $16
        .byte   $06
        .byte   $02
        .byte   $07
        .byte   $03
        .byte   $07
        .byte   $04
        .byte   $07
        .byte   $04
        .byte   $20
        .byte   $20
        .byte   $05
        .byte   $10
        .byte   $01
        .byte   $02
        .byte   $01
        .byte   $02
        .byte   $a8
        .byte   $b9
        .byte   $28
        .byte   $14
        .byte   $be
        .byte   $30
        .byte   $14
        .byte   $38
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $a9
        .byte   $f1
        .byte   $a0
        .byte   $1f
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a2
        .byte   $00
        .byte   $a9
        .byte   $20
        .byte   $38
        .byte   $20
        .byte   $8b
        .byte   $14
        .byte   $88
        .byte   $10
        .byte   $f5
        .byte   $60
        .byte   $a9
        .byte   $f1
        .byte   $a0
        .byte   $1f
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a9
        .byte   $0e
        .byte   $a2
        .byte   $01
        .byte   $38
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $e6
        .byte   $f9
        .byte   $e6
        .byte   $f9
        .byte   $ac
        .byte   $c2
        .byte   $1b
        .byte   $b9
        .byte   $7c
        .byte   $14
        .byte   $4c
        .byte   $c3
        .byte   $16
        .byte   $01
        .byte   $02
        .byte   $04
        .byte   $08
        .byte   $16
        .text   "$2@hv"
        .byte   $64
        .byte   $72
        .byte   $4c
        .byte   $af
        .byte   $14
        .byte   $4c
        .byte   $b1
        .byte   $14
        .byte   $4c
        .byte   $d8
        .byte   $14
        .byte   $4c
        .byte   $43
        .byte   $15
        .byte   $4c
        .byte   $46
        .byte   $15
        .byte   $4c
        .byte   $49
        .byte   $15
        .byte   $4c
        .byte   $65
        .byte   $15
        .byte   $4c
        .byte   $a2
        .byte   $15
        .byte   $4c
        .byte   $d5
        .byte   $15
        .byte   $4c
        .byte   $22
        .byte   $16
        .byte   $4c
        .byte   $2d
        .byte   $16
        .byte   $4c
        .byte   $47
        .byte   $16
        .byte   $4c
        .byte   $cf
        .byte   $15
        .byte   $a0
        .byte   $00
        .byte   $b0
        .byte   $11
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $69
        .byte   $78
        .byte   $85
        .byte   $fa
        .byte   $b1
        .byte   $f9
        .byte   $aa
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $b1
        .byte   $f9
        .byte   $18
        .byte   $60
        .byte   $91
        .byte   $f9
        .byte   $48
        .byte   $a5
        .byte   $fa
        .byte   $48
        .byte   $18
        .byte   $69
        .byte   $78
        .byte   $85
        .byte   $fa
        .byte   $8a
        .byte   $91
        .byte   $f9
        .byte   $68
        .byte   $85
        .byte   $fa
        .byte   $38
        .byte   $68
        .byte   $60
        .byte   $78
        .byte   $f8
        .byte   $a0
        .byte   $03
        .byte   $18
        .byte   $b9
        .byte   $89
        .byte   $1b
        .byte   $79
        .byte   $84
        .byte   $1b
        .byte   $99
        .byte   $84
        .byte   $1b
        .byte   $88
        .byte   $10
        .byte   $f4
        .byte   $d8
        .byte   $a9
        .byte   $0b
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $1e
        .byte   $85
        .byte   $fa
        .byte   $a9
        .byte   $80
        .byte   $85
        .byte   $fb
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $fc
        .byte   $20
        .byte   $0d
        .byte   $15
        .byte   $a9
        .byte   $21
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $1e
        .byte   $85
        .byte   $fa
        .byte   $a9
        .byte   $84
        .byte   $85
        .byte   $fb
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $fc
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $fd
        .byte   $85
        .byte   $fe
        .byte   $a4
        .byte   $fe
        .byte   $c0
        .byte   $04
        .byte   $f0
        .byte   $14
        .byte   $b1
        .byte   $fb
        .text   "hjjjj ."
        .byte   $15
        .byte   $68
        .byte   $29
        .byte   $0f
        .byte   $20
        .byte   $2e
        .byte   $15
        .byte   $e6
        .byte   $fe
        .byte   $d0
        .byte   $e6
        .byte   $60
        .byte   $f0
        .byte   $02
        .byte   $c6
        .byte   $fd
        .byte   $24
        .byte   $fd
        .byte   $30
        .byte   $03
        .byte   $a2
        .byte   $00
        .byte   $2c
        .byte   $a2
        .byte   $07
        .byte   $09
        .byte   $30
        .byte   $20
        .byte   $d1
        .byte   $15
        .byte   $e6
        .byte   $f9
        .byte   $60
        .byte   $a0
        .byte   $00
        .byte   $2c
        .byte   $a0
        .byte   $04
        .byte   $2c
        .byte   $a0
        .byte   $09
        .byte   $a9
        .byte   $80
        .byte   $85
        .byte   $fb
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $fc
        .byte   $a9
        .byte   $25
        .byte   $85
        .byte   $fd
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $fe
        .byte   $b1
        .byte   $fd
        .byte   $91
        .byte   $fb
        .byte   $c8
        .byte   $c0
        .byte   $50
        .byte   $d0
        .byte   $f7
        .byte   $60
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $22
        .byte   $91
        .byte   $ad
        .byte   $20
        .byte   $91
        .byte   $49
        .byte   $ff
        .byte   $29
        .byte   $80
        .byte   $2a
        .byte   $08
        .byte   $a9
        .byte   $ff
        .byte   $8d
        .byte   $22
        .byte   $91
        .byte   $ad
        .byte   $11
        .byte   $91
        .byte   $49
        .byte   $ff
        .text   ")",$1c,"jj(*I"
        .byte   $01
        .byte   $f0
        .byte   $0f
        .byte   $c9
        .byte   $02
        .byte   $f0
        .byte   $0e
        .byte   $c9
        .byte   $04
        .byte   $f0
        .byte   $0d
        .byte   $c9
        .byte   $08
        .byte   $d0
        .byte   $0e
        .byte   $a9
        .byte   $03
        .byte   $2c
        .byte   $a9
        .byte   $00
        .byte   $2c
        .byte   $a9
        .byte   $01
        .byte   $2c
        .byte   $a9
        .byte   $02
        .byte   $8d
        .byte   $b8
        .byte   $1b
        .byte   $60
        .byte   $ad
        .byte   $a9
        .byte   $1b
        .byte   $ac
        .byte   $aa
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $18
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $c9
        .byte   $11
        .byte   $d0
        .byte   $10
        .byte   $ad
        .byte   $ab
        .byte   $1b
        .byte   $f0
        .byte   $0e
        .byte   $c9
        .byte   $01
        .byte   $f0
        .byte   $0d
        .byte   $c9
        .byte   $02
        .byte   $f0
        .byte   $0c
        .byte   $a9
        .byte   $18
        .byte   $2c
        .byte   $a9
        .byte   $11
        .byte   $2c
        .byte   $a9
        .byte   $0d
        .byte   $2c
        .byte   $a9
        .byte   $19
        .byte   $2c
        .byte   $a9
        .byte   $10
        .byte   $a2
        .byte   $07
        .byte   $38
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $ad
        .byte   $a9
        .byte   $1b
        .byte   $ac
        .byte   $aa
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a9
        .byte   $b4
        .byte   $a0
        .byte   $16
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $8c
        .byte   $15
        .byte   $03
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $a2
        .byte   $a9
        .byte   $1a
        .byte   $20
        .byte   $cf
        .byte   $15
        .byte   $58
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $05
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $1b
        .byte   $20
        .byte   $cf
        .byte   $15
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $09
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $1c
        .byte   $20
        .byte   $cf
        .byte   $15
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $0d
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $20
        .byte   $d1
        .byte   $15
        .byte   $78
        .byte   $a9
        .byte   $56
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $a9
        .byte   $13
        .byte   $8d
        .byte   $15
        .byte   $03
        .byte   $60
        .byte   $18
        .byte   $a9
        .byte   $d8
        .byte   $6d
        .byte   $88
        .byte   $1b
        .byte   $a0
        .byte   $1e
        .byte   $20
        .byte   $db
        .byte   $15
        .byte   $a9
        .byte   $c2
        .byte   $a0
        .byte   $1f
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $8d
        .byte   $a9
        .byte   $1b
        .byte   $8c
        .byte   $aa
        .byte   $1b
        .byte   $a9
        .byte   $01
        .byte   $8d
        .byte   $ab
        .byte   $1b
        .byte   $8d
        .byte   $b8
        .byte   $1b
        .byte   $a9
        .byte   $10
        .byte   $d0
        .byte   $88
        .byte   $a9
        .byte   $03
        .byte   $85
        .byte   $8f
        .byte   $a9
        .byte   $86
        .byte   $85
        .byte   $8d
        .byte   $a9
        .byte   $1b
        .byte   $85
        .byte   $8e
        .byte   $18
        .byte   $a9
        .byte   $07
        .byte   $65
        .byte   $8d
        .byte   $85
        .byte   $8d
        .byte   $a0
        .byte   $00
        .byte   $b1
        .byte   $8d
        .byte   $85
        .byte   $f9
        .byte   $c8
        .byte   $b1
        .byte   $8d
        .byte   $85
        .byte   $fa
        .byte   $a0
        .byte   $06
        .byte   $b1
        .byte   $8d
        .byte   $aa
        .byte   $88
        .byte   $b1
        .byte   $8d
        .byte   $20
        .byte   $d1
        .byte   $15
        .byte   $a6
        .byte   $8f
        .byte   $bd
        .byte   $b0
        .byte   $16
        .byte   $a0
        .byte   $00
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $a9
        .byte   $1e
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $a6
        .byte   $8f
        .byte   $bd
        .byte   $21
        .byte   $1b
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $a9
        .byte   $00
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $c8
        .byte   $91
        .byte   $8d
        .byte   $88
        .byte   $a9
        .byte   $20
        .byte   $91
        .byte   $8d
        .byte   $a0
        .byte   $00
        .byte   $b1
        .byte   $8d
        .byte   $85
        .byte   $f9
        .byte   $c8
        .byte   $b1
        .byte   $8d
        .byte   $85
        .byte   $fa
        .byte   $c8
        .byte   $b1
        .byte   $8d
        .byte   $aa
        .byte   $a9
        .byte   $0e
        .byte   $20
        .byte   $d1
        .byte   $15
        .byte   $c6
        .byte   $8f
        .byte   $10
        .byte   $a4
        .byte   $60
        .byte   $fb
        .byte   $fc
        .byte   $fd
        .byte   $fe
        .byte   $4c
        .byte   $e1
        .byte   $17
        .byte   $4c
        .byte   $cf
        .byte   $16
        .byte   $4c
        .byte   $f0
        .byte   $16
        .byte   $4c
        .byte   $21
        .byte   $17
        .byte   $4c
        .byte   $a0
        .byte   $17
        .byte   $4c
        .byte   $e7
        .byte   $17
        .byte   $4c
        .byte   $15
        .byte   $18
        .byte   $4c
        .byte   $20
        .byte   $18
        .byte   $4c
        .byte   $6b
        .byte   $18
        .byte   $20
        .byte   $97
        .byte   $14
        .byte   $20
        .byte   $cc
        .byte   $16
        .byte   $a9
        .byte   $d7
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $1e
        .byte   $85
        .byte   $fa
        .byte   $ac
        .byte   $88
        .byte   $1b
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $c8
        .byte   $c0
        .byte   $04
        .byte   $f0
        .byte   $06
        .byte   $38
        .byte   $20
        .byte   $8b
        .byte   $14
        .byte   $b0
        .byte   $f5
        .byte   $60
        .byte   $ad
        .byte   $bc
        .byte   $1b
        .byte   $d0
        .byte   $28
        .byte   $ce
        .byte   $bd
        .byte   $1b
        .byte   $10
        .byte   $23
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $bc
        .byte   $1b
        .byte   $8d
        .byte   $bd
        .byte   $1b
        .byte   $8d
        .byte   $c2
        .byte   $1b
        .byte   $8d
        .byte   $be
        .byte   $1b
        .byte   $a9
        .byte   $03
        .byte   $8d
        .byte   $90
        .byte   $1b
        .byte   $a9
        .byte   $04
        .byte   $8d
        .byte   $97
        .byte   $1b
        .byte   $a9
        .byte   $07
        .byte   $8d
        .byte   $9e
        .byte   $1b
        .byte   $a9
        .byte   $02
        .byte   $8d
        .byte   $a5
        .byte   $1b
        .byte   $60
        .byte   $ce
        .byte   $bc
        .byte   $1b
        .byte   $60
        .byte   $ad
        .byte   $8d
        .byte   $1b
        .byte   $ac
        .byte   $8e
        .byte   $1b
        .byte   $20
        .byte   $92
        .byte   $17
        .byte   $90
        .byte   $06
        .byte   $a9
        .byte   $8d
        .byte   $a0
        .byte   $1b
        .byte   $d0
        .byte   $26
        .byte   $ad
        .byte   $a2
        .byte   $1b
        .byte   $ac
        .byte   $a3
        .byte   $1b
        .byte   $20
        .byte   $92
        .byte   $17
        .byte   $90
        .byte   $06
        .byte   $a9
        .byte   $a2
        .byte   $a0
        .byte   $1b
        .byte   $d0
        .byte   $15
        .byte   $ad
        .byte   $94
        .byte   $1b
        .byte   $ac
        .byte   $95
        .byte   $1b
        .byte   $20
        .byte   $92
        .byte   $17
        .byte   $90
        .byte   $06
        .byte   $a9
        .byte   $94
        .byte   $a0
        .byte   $1b
        .byte   $d0
        .byte   $04
        .byte   $a9
        .byte   $9b
        .byte   $a0
        .byte   $1b
        .byte   $85
        .byte   $8d
        .byte   $84
        .byte   $8e
        .byte   $a0
        .byte   $00
        .byte   $a9
        .byte   $fb
        .byte   $85
        .byte   $f9
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $a9
        .byte   $1e
        .byte   $85
        .byte   $fa
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $c8
        .byte   $b1
        .byte   $8d
        .byte   $aa
        .byte   $a9
        .byte   $0e
        .byte   $20
        .byte   $dd
        .byte   $17
        .byte   $a0
        .byte   $04
        .byte   $a9
        .byte   $00
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $b1
        .byte   $8d
        .byte   $c9
        .byte   $0b
        .byte   $d0
        .byte   $03
        .byte   $ce
        .byte   $ba
        .byte   $1b
        .byte   $a9
        .byte   $20
        .byte   $91
        .byte   $8d
        .byte   $c8
        .byte   $a9
        .byte   $00
        .byte   $91
        .byte   $8d
        .byte   $8d
        .byte   $c1
        .byte   $1b
        .byte   $60
        .byte   $cd
        .byte   $a9
        .byte   $1b
        .byte   $d0
        .byte   $07
        .byte   $cc
        .byte   $aa
        .byte   $1b
        .byte   $d0
        .byte   $02
        .byte   $38
        .byte   $24
        .byte   $18
        .byte   $60
        .byte   $ad
        .byte   $8d
        .byte   $1b
        .byte   $ac
        .byte   $8e
        .byte   $1b
        .byte   $ae
        .byte   $90
        .byte   $1b
        .byte   $20
        .byte   $cd
        .byte   $17
        .byte   $ad
        .byte   $94
        .byte   $1b
        .byte   $ac
        .byte   $95
        .byte   $1b
        .byte   $ae
        .byte   $97
        .byte   $1b
        .byte   $20
        .byte   $cd
        .byte   $17
        .byte   $ad
        .byte   $9b
        .byte   $1b
        .byte   $ac
        .byte   $9c
        .byte   $1b
        .byte   $ae
        .byte   $9e
        .byte   $1b
        .byte   $20
        .byte   $cd
        .byte   $17
        .byte   $ad
        .byte   $a2
        .byte   $1b
        .byte   $ac
        .byte   $a3
        .byte   $1b
        .byte   $ae
        .byte   $a5
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $8a
        .byte   $48
        .byte   $18
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $49
        .byte   $01
        .byte   $a8
        .byte   $68
        .byte   $aa
        .byte   $98
        .byte   $38
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $20
        .byte   $ea
        .byte   $ff
        .byte   $4c
        .byte   $15
        .byte   $eb
        .text   "hjjjjP"
        .byte   $0b
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $20
        .byte   $dd
        .byte   $17
        .byte   $e6
        .byte   $f9
        .byte   $d0
        .byte   $06
        .byte   $09
        .byte   $30
        .byte   $a2
        .byte   $07
        .byte   $d0
        .byte   $f3
        .byte   $68
        .byte   $29
        .byte   $0f
        .byte   $09
        .byte   $30
        .byte   $a2
        .byte   $07
        .byte   $20
        .byte   $dd
        .byte   $17
        .byte   $e6
        .byte   $f9
        .byte   $a9
        .byte   $30
        .byte   $20
        .byte   $88
        .byte   $14
        .byte   $e6
        .byte   $f9
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $a9
        .byte   $00
        .byte   $a0
        .byte   $04
        .byte   $99
        .byte   $0a
        .byte   $90
        .byte   $88
        .byte   $10
        .byte   $fa
        .byte   $60
        .byte   $18
        .byte   $a9
        .byte   $9f
        .byte   $69
        .byte   $57
        .byte   $85
        .byte   $f9
        .byte   $a9
        .byte   $1b
        .byte   $69
        .byte   $01
        .byte   $85
        .byte   $fa
        .byte   $a9
        .byte   $57
        .byte   $85
        .byte   $f7
        .byte   $a9
        .byte   $1d
        .byte   $85
        .byte   $f8
        .byte   $a0
        .byte   $00
        .byte   $b1
        .byte   $f9
        .byte   $91
        .byte   $f7
        .byte   $a5
        .byte   $f9
        .byte   $d0
        .byte   $02
        .byte   $c6
        .byte   $fa
        .byte   $c6
        .byte   $f9
        .byte   $a5
        .byte   $f7
        .byte   $d0
        .byte   $02
        .byte   $c6
        .byte   $f8
        .byte   $c6
        .byte   $f7
        .byte   $a5
        .byte   $f8
        .byte   $c9
        .byte   $1b
        .byte   $d0
        .byte   $e6
        .byte   $a9
        .byte   $00
        .byte   $a0
        .byte   $1d
        .byte   $85
        .byte   $f7
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $f8
        .byte   $a9
        .byte   $81
        .byte   $85
        .byte   $fa
        .byte   $a0
        .byte   $ff
        .byte   $b1
        .byte   $f9
        .byte   $91
        .byte   $f7
        .byte   $88
        .byte   $c0
        .byte   $57
        .byte   $d0
        .byte   $f7
        .byte   $60
        .byte   $a9
        .byte   $b4
        .byte   $a0
        .byte   $16
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $8c
        .byte   $15
        .byte   $03
        .byte   $a9
        .byte   $08
        .byte   $8d
        .byte   $0f
        .byte   $90
        .byte   $a0
        .byte   $00
        .byte   $b9
        .byte   $ff
        .byte   $18
        .byte   $c9
        .byte   $00
        .byte   $f0
        .byte   $06
        .byte   $20
        .byte   $d2
        .byte   $ff
        .byte   $c8
        .byte   $d0
        .byte   $f3
        .byte   $78
        .byte   $a9
        .byte   $44
        .byte   $a0
        .byte   $1a
        .byte   $85
        .byte   $f7
        .byte   $84
        .byte   $f8
        .byte   $a9
        .byte   $2b
        .byte   $a0
        .byte   $1e
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a2
        .byte   $00
        .byte   $8a
        .byte   $48
        .byte   $a0
        .byte   $00
        .byte   $e6
        .byte   $f7
        .byte   $d0
        .byte   $02
        .byte   $e6
        .byte   $f8
        .byte   $b1
        .byte   $f7
        .text   "hjjjj "
        .byte   $e1
        .byte   $18
        .byte   $68
        .byte   $29
        .byte   $0f
        .byte   $20
        .byte   $e1
        .byte   $18
        .byte   $68
        .byte   $aa
        .byte   $e8
        .byte   $8a
        .byte   $48
        .byte   $e0
        .byte   $dc
        .byte   $d0
        .byte   $e1
        .byte   $68
        .byte   $a9
        .byte   $1e
        .byte   $85
        .byte   $fa
        .byte   $a9
        .byte   $fb
        .byte   $85
        .byte   $f9
        .byte   $a0
        .byte   $03
        .byte   $be
        .byte   $21
        .byte   $1b
        .byte   $a9
        .byte   $0e
        .byte   $38
        .byte   $20
        .byte   $8b
        .byte   $14
        .byte   $88
        .byte   $10
        .byte   $f4
        .byte   $a9
        .byte   $56
        .byte   $a0
        .byte   $13
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $8c
        .byte   $15
        .byte   $03
        .byte   $60
        .byte   $e6
        .byte   $f9
        .byte   $d0
        .byte   $02
        .byte   $e6
        .byte   $fa
        .byte   $c9
        .byte   $0b
        .byte   $90
        .byte   $09
        .byte   $f0
        .byte   $0d
        .byte   $c9
        .byte   $0c
        .byte   $f0
        .byte   $06
        .byte   $a2
        .byte   $07
        .byte   $2c
        .byte   $a2
        .byte   $06
        .byte   $2c
        .byte   $a2
        .byte   $02
        .byte   $2c
        .byte   $a2
        .byte   $05
        .byte   $4c
        .byte   $dd
        .byte   $17
        .text   $93,$9e,"()*( #$%&' ",$0d,$9e,"     #$%&' ",$0d
        .byte   $13
        .byte   $00
        .byte   $a5
        .byte   $00
        .byte   $c9
        .byte   $0c
        .byte   $90
        .byte   $04
        .byte   $a9
        .byte   $0b
        .byte   $85
        .byte   $00
        .byte   $c6
        .byte   $00
        .byte   $30
        .byte   $f8
        .byte   $2c
        .byte   $be
        .byte   $1b
        .byte   $30
        .byte   $34
        .byte   $a4
        .byte   $00
        .byte   $b9
        .byte   $4f
        .byte   $19
        .byte   $8d
        .byte   $0c
        .byte   $90
        .byte   $a9
        .byte   $05
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $a5
        .byte   $01
        .byte   $f0
        .byte   $0b
        .byte   $a8
        .byte   $c6
        .byte   $01
        .byte   $a9
        .byte   $0f
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $b9
        .byte   $5b
        .byte   $19
        .byte   $8d
        .byte   $0a
        .byte   $90
        .byte   $60
        .byte   $d8
        .byte   $da
        .byte   $dc
        .byte   $de
        .byte   $e0
        .byte   $e2
        .byte   $e1
        .byte   $df
        .byte   $dd
        .byte   $db
        .byte   $d9
        .byte   $d7
        .byte   $00
        .byte   $90
        .byte   $92
        .byte   $94
        .byte   $96
        .byte   $94
        .byte   $92
        .byte   $90
        .byte   $ad
        .byte   $bd
        .byte   $1b
        .byte   $d0
        .byte   $07
        .byte   $ad
        .byte   $bc
        .byte   $1b
        .byte   $c9
        .byte   $40
        .byte   $90
        .byte   $13
        .byte   $a9
        .byte   $00
        .byte   $8d
        .byte   $0a
        .byte   $90
        .byte   $a9
        .byte   $0f
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $a4
        .byte   $00
        .byte   $b9
        .byte   $8d
        .byte   $19
        .byte   $8d
        .byte   $0c
        .byte   $90
        .byte   $60
        .byte   $a9
        .byte   $08
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $a9
        .byte   $d8
        .byte   $8d
        .byte   $0c
        .byte   $90
        .byte   $60
        .byte   $d8
        .byte   $d9
        .byte   $da
        .byte   $db
        .byte   $dc
        .byte   $dd
        .byte   $de
        .byte   $df
        .byte   $e0
        .byte   $e1
        .byte   $e2
        .byte   $e3
        .byte   $20
        .byte   $c0
        .byte   $16
        .byte   $20
        .byte   $2f
        .byte   $1a
        .byte   $20
        .byte   $c6
        .byte   $16
        .byte   $a9
        .byte   $cd
        .byte   $8d
        .byte   $0c
        .byte   $90
        .byte   $a9
        .byte   $0f
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $58
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $03
        .byte   $d0
        .byte   $fa
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $a2
        .byte   $ce
        .byte   $0c
        .byte   $90
        .byte   $ad
        .byte   $0c
        .byte   $90
        .byte   $c9
        .byte   $a5
        .byte   $d0
        .byte   $ec
        .byte   $78
        .byte   $20
        .byte   $c6
        .byte   $16
        .byte   $a9
        .byte   $0f
        .byte   $8d
        .byte   $0e
        .byte   $90
        .byte   $a9
        .byte   $80
        .byte   $8d
        .byte   $0d
        .byte   $90
        .byte   $8d
        .byte   $0a
        .byte   $90
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $a2
        .byte   $ad
        .byte   $a9
        .byte   $1b
        .byte   $ac
        .byte   $aa
        .byte   $1b
        .byte   $85
        .byte   $f9
        .byte   $84
        .byte   $fa
        .byte   $a9
        .byte   $1a
        .byte   $20
        .byte   $3f
        .byte   $1a
        .byte   $58
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $04
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $1b
        .byte   $20
        .byte   $3f
        .byte   $1a
        .byte   $ce
        .byte   $0e
        .byte   $90
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $09
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $1c
        .byte   $20
        .byte   $3f
        .byte   $1a
        .byte   $ce
        .byte   $0e
        .byte   $90
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $0e
        .byte   $90
        .byte   $fa
        .byte   $a9
        .byte   $20
        .byte   $a2
        .byte   $00
        .byte   $20
        .byte   $41
        .byte   $1a
        .byte   $ce
        .byte   $0e
        .byte   $90
        .byte   $f0
        .byte   $0c
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $a2
        .byte   $a5
        .byte   $a2
        .byte   $c9
        .byte   $05
        .byte   $b0
        .byte   $f1
        .byte   $90
        .byte   $f8
        .byte   $20
        .byte   $c6
        .byte   $16
        .byte   $78
        .byte   $a9
        .byte   $13
        .byte   $8d
        .byte   $15
        .byte   $03
        .byte   $a9
        .byte   $56
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $60
        .byte   $78
        .byte   $a9
        .byte   $b4
        .byte   $a0
        .byte   $16
        .byte   $8d
        .byte   $14
        .byte   $03
        .byte   $8c
        .byte   $15
        .byte   $03
        .byte   $a9
        .byte   $00
        .byte   $85
        .byte   $a2
        .byte   $60
        .byte   $a2
        .byte   $07
        .byte   $38
        .byte   $4c
        .byte   $88
        .byte   $14
        .byte   $31
        .fill   9,$11
        .byte   $14
        .byte   $2b
        .byte   $bb
        .byte   $cb
        .fill   5,$bb
        .byte   $bc
        .byte   $bb
        .byte   $b2
        .byte   $2b
        .byte   $11
        .byte   $11
        .byte   $11
        .byte   $b1
        .byte   $77
        .byte   $1b
        .byte   $11
        .byte   $11
        .byte   $11
        .byte   $b2
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $22
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .byte   $2b
        .byte   $11
        .byte   $1b
        .byte   $2b
        .byte   $2b
        .byte   $65
        .byte   $b2
        .byte   $b2
        .byte   $b1
        .byte   $11
        .byte   $b2
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $2b
        .byte   $2b
        .byte   $bb
        .byte   $b2
        .byte   $b2
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .byte   $2b
        .byte   $11
        .byte   $1b
        .byte   $2b
        .byte   $61
        .byte   $11
        .byte   $15
        .byte   $b2
        .byte   $b3
        .byte   $11
        .byte   $19
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .byte   $b2
        .byte   $dd
        .byte   $d2
        .byte   $a1
        .byte   $11
        .byte   $4b
        .byte   $2b
        .byte   $31
        .byte   $11
        .byte   $14
        .byte   $b2
        .byte   $b6
        .byte   $11
        .byte   $15
        .byte   $61
        .byte   $11
        .byte   $5b
        .byte   $2b
        .byte   $2e
        .byte   $ee
        .byte   $e0
        .fill   8,$bb
        .byte   $61
        .byte   $11
        .byte   $15
        .byte   $b2
        .byte   $b3
        .byte   $11
        .byte   $14
        .byte   $31
        .byte   $11
        .byte   $4b
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .byte   $b6
        .byte   $11
        .byte   $19
        .byte   $a1
        .byte   $11
        .text   "[++4"
        .byte   $b2
        .byte   $b2
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .byte   $2b
        .byte   $bb
        .byte   $bb
        .byte   $2b
        .byte   $2b
        .byte   $22
        .byte   $b2
        .byte   $b2
        .byte   $b1
        .byte   $11
        .byte   $b2
        .text   "+++++",$22
        .byte   $b2
        .byte   $b2
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .text   "+++++",$22
        .byte   $b2
        .byte   $b2
        .byte   $b1
        .byte   $11
        .byte   $b2
        .text   "+++++",$22
        .byte   $b2
        .byte   $b2
        .byte   $bb
        .byte   $bb
        .byte   $b2
        .text   "+++++"
        .byte   $65
        .byte   $b2
        .byte   $b2
        .byte   $b1
        .byte   $11
        .byte   $b2
        .byte   $2b
        .byte   $bb
        .byte   $cb
        .fill   5,$bb
        .byte   $bc
        .byte   $bb
        .byte   $b2
        .byte   $61
        .fill   9,$11
        .byte   $15
        .byte   $02
        .byte   $07
        .byte   $04
        .byte   $03
        .fill   8,$00
        .byte   $03
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $fe
        .byte   $1e
        .byte   $03
        .byte   $03
        .byte   $00
        .byte   $20
        .byte   $00
        .byte   $fb
        .byte   $1e
        .byte   $04
        .byte   $04
        .byte   $00
        .byte   $20
        .byte   $00
        .byte   $fd
        .byte   $1e
        .byte   $07
        .byte   $07
        .byte   $00
        .byte   $20
        .byte   $00
        .byte   $fc
        .byte   $1e
        .byte   $02
        .byte   $02
        .byte   $00
        .byte   $20
        .byte   $00
        .byte   $c2
        .byte   $1f
        .byte   $01
        .byte   $10
        .byte   $20
        .byte   $0c
        .byte   $18
        .fill   8,$00
        .byte   $01
        .byte   $00
        .byte   $c4
        .fill   8,$00
        .byte   $a0
        .byte   $00
        .byte   $84
        .byte   $00
        .byte   $b9
        .byte   $00
        .byte   $1e
        .byte   $20
        .byte   $84
        .byte   $1b
        .byte   $b9
        .byte   $00
        .byte   $1f
        .byte   $20
        .byte   $84
        .byte   $1b
        .byte   $c8
        .byte   $d0
        .byte   $f1
        .byte   $a5
        .byte   $00
        .byte   $c9
        .byte   $09
        .byte   $d0
        .byte   $fc
        .byte   $4c
        .byte   $c9
        .byte   $16
        .byte   $a2
        .byte   $07
        .byte   $dd
        .byte   $97
        .byte   $1b
        .byte   $f0
        .byte   $09
        .byte   $ca
        .byte   $10
        .byte   $f8
        .byte   $c9
        .byte   $20
        .byte   $f0
        .byte   $04
        .byte   $d0
        .byte   $fa
        .byte   $e6
        .byte   $00
        .byte   $60
        .byte   $12
        .byte   $05
        .byte   $01
        .byte   $04
        .byte   $19
        .byte   $2e
        .byte   $15
        .byte   $0e
        .byte   $28
        .byte   $14
        .byte   $28
        .byte   $14
        .byte   $28
        .byte   $14
        .byte   $28
        .byte   $14
        .byte   $00
        .byte   $00
        .byte   $ff
        .byte   $ff
        .byte   $ff
        .byte   $ff
        .byte   $00
        .byte   $00
        .text   "<<<<<<<<"
        .byte   $00
        .byte   $00
        .text   "????<<"
        .byte   $00
        .byte   $00
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .text   "<<<<"
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .byte   $00
        .byte   $00
        .text   "<<????"
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $ff
        .byte   $ff
        .byte   $ff
        .byte   $ff
        .byte   $3c
        .byte   $3c
        .fill   8,$00
        .byte   $3c
        .byte   $3c
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .byte   $fc
        .text   "<<<<????<<"
        .byte   $00
        .byte   $00
        .byte   $18
        .byte   $3c
        .byte   $3c
        .byte   $18
        .byte   $00
        .byte   $00
        .byte   $00
        .byte   $18
        .byte   $3c
        .byte   $7e
        .byte   $7e
        .byte   $3c
        .byte   $18
        .byte   $00
        .byte   $1c
        .byte   $3e
        .byte   $70
        .byte   $60
        .byte   $60
        .byte   $70
        .byte   $3e
        .byte   $1c
        .byte   $3c
        .byte   $7e
        .byte   $6a
        .byte   $6a
        .byte   $6a
        .byte   $7e
        .byte   $2a
        .byte   $2a
        .byte   $3c
        .byte   $7e
        .byte   $6a
        .byte   $6a
        .byte   $6a
        .byte   $7e
        .byte   $54
        .byte   $54
        .byte   $18
        .byte   $3c
        .byte   $7e
        .byte   $e7
        .byte   $c3
        .byte   $c3
        .byte   $42
        .byte   $00
        .byte   $18
        .byte   $3c
        .byte   $7e
        .byte   $7e
        .byte   $7e
        .byte   $3c
        .byte   $18
        .byte   $00
        .byte   $08
        .byte   $18
        .byte   $3c
        .byte   $3c
        .byte   $7e
        .byte   $7e
        .byte   $ff
        .byte   $18
        .byte   $06
        .byte   $8e
        .byte   $7e
        .byte   $3e
        .byte   $1e
        .byte   $02
        .byte   $02
        .byte   $07
        .byte   $e0
        .byte   $58
        .byte   $44
        .byte   $22
        .byte   $77
        .byte   $77
        .byte   $77
        .byte   $22
        .byte   $08
        .byte   $1c
        .byte   $ff
        .byte   $7e
        .byte   $3c
        .byte   $7e
        .byte   $63
        .byte   $41
        .byte   $00
        .byte   $18
        .byte   $3f
        .byte   $7d
        .byte   $7f
        .byte   $7e
        .byte   $7e
        .byte   $7e
        .byte   $0f
        .byte   $08
        .byte   $0f
        .byte   $08
        .byte   $08
        .byte   $78
        .byte   $78
        .byte   $70
        .byte   $38
        .byte   $7c
        .byte   $0e
        .byte   $06
        .byte   $06
        .byte   $0e
        .byte   $7c
        .byte   $38
        .byte   $00
        .byte   $42
        .byte   $c3
        .byte   $c3
        .byte   $e7
        .byte   $7e
        .byte   $3c
        .byte   $00
        .byte   $c3
        .byte   $e7
        .byte   $7e
        .byte   $3c
        .byte   $3c
        .byte   $7e
        .byte   $e7
        .byte   $c3
        .byte   $89
        .byte   $4a
        .byte   $2c
        .byte   $ff
        .byte   $18
        .byte   $34
        .byte   $52
        .byte   $91
        .byte   $00
        .byte   $40
        .byte   $00
        .byte   $02
        .byte   $00
        .byte   $00
        .byte   $02
        .byte   $20
        .byte   $00
        .byte   $00
        .text   $07,$1f,"?8"
        .fill   5,$70
        .text   "8?",$1f,$07
        .fill   6,$00
        .byte   $fc
        .byte   $f8
        .byte   $f0
        .fill   9,$00
        .byte   $f0
        .byte   $f8
        .byte   $fc
        .fill   12,$00
        .text   "<b@<"
        .byte   $02
        .byte   $42
        .byte   $3c
        .byte   $00
        .text   $1c,$22,"@@@",$22,$1c
        .byte   $00
        .byte   $18
        .text   "$bbb$"
        .byte   $18
        .byte   $00
        .byte   $7c
        .byte   $42
        .byte   $42
        .byte   $7c
        .byte   $48
        .byte   $44
        .byte   $42
        .byte   $00
        .byte   $7e
        .byte   $40
        .byte   $40
        .byte   $70
        .byte   $40
        .byte   $40
        .byte   $7e
        .byte   $00
        .byte   $42
        .byte   $42
        .byte   $42
        .byte   $7e
        .byte   $42
        .byte   $42
        .byte   $42
        .byte   $00
        .byte   $1c
        .fill   5,$08
        .byte   $1c
        .byte   $00
        .text   $1c,$22,"@nb",$22,$1c
        .byte   $00
        .text   "         e6fa            d011            297f            858f "
        .text   "           38              a5f9            e58f            85f"
        .text   "9            a5fa            e900            85fa            1"
        .text   "8              20@sdh          aa              68             "
        .text   " a8                                                           "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                                              "
        .text   "                                 "
